### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by jedisct1** [cloudflare/go#11]
Hi,

What is the license of your AES-GCM implementation? Is it exclusively the Go license?

I'd love to merge it to Libsodium, but that project is using the ISC license, which is also a BSD-like license, but that might not be compatible with the Go license.

**Comment by vkrasnov** [comment]
I don't decide about the license state, but I wonder why would you rather port a go implementation, instead using something like OpenSSL one, that supports a wider range of architectures?

**Comment by FiloSottile** [comment]
All patches landed in the main Go tree, so are available under the same license as the Go code.
