### ISSUE TITLE
Any of the improvements being submitted to Go main branch?

### ISSUE THREAD

**Issue by diegomontoya** [cloudflare/go#12]
I would like to use the improvements but would rather not hand merge the changes with the current Go 1.6 tip code if some or most of the improvements is already taken in by Go. 

Can you guys confirm or deny if any of the improvement made it to the official Go code?

**Comment by vkrasnov** [comment]
All of the improvements are now in the Go trunk.

https://github.com/golang/go/commit/7bacfc640fba4fb2e50bbcc16a4c15fe4bf5b870
https://github.com/golang/go/commit/efeeee38c9aa30d2bdcb9d150c6e76ada01c5145
https://github.com/golang/go/commit/9279684908673448aacb4eaea71990ef96fce645

**Comment by diegomontoya** [comment]
Awesome. =)
