### ISSUE TITLE
signatureSchemeForDelegatedCredential is unneccessary

### ISSUE THREAD

**Issue by jhoyla** [cloudflare/go#127]
`signatureSchemeForDelegatedCredential` returns the list of supported signature schemes for a delegated credential; however, per the spec, DCs are explicitly restricted to a single `SignatureAlgorithm` defined in the `dc_cert_verify_algorithm` field.
We can simply use `dc_cert_verify_algorithm`, rather than call this function.

**Comment by claucece** [comment]
Def agree. It was requested in a PR review, but it is better to unify them.
