### ISSUE TITLE
`selectSignatureSchemeDC` does not account for the client's `supported_algorithms`

### ISSUE THREAD

**Issue by jhoyla** [cloudflare/go#128]
`selectSignatureSchemeDC` only checks the client's `supportedSignatureAlgorithmsDC` field. Per the [spec](https://datatracker.ietf.org/doc/html/draft-ietf-tls-subcerts-15#section-4.1.1) the selected signature scheme MUST be in both the `supportedSignatureAlgorithmsDC` and `supportedSignatureAlgorithms` fields.

**Comment by claucece** [comment]
YESSSS!!! Thank you for this!!
