### ISSUE TITLE
PQ cipher suites are not used even when specified in tls.Config

### ISSUE THREAD

**Issue by ameshkov** [cloudflare/go#154]
Even when pq cipher suites are explicitly specified in `tls.Config`:
```
	conf := &tls.Config{
		CipherSuites: []uint16{
			uint16(ctls.X25519Kyber768Draft00),
		},
	}
```

They won't be used in the TLS Client Hello due to the fact that these cipher suites aren't present in the `cipherSuitesPreferenceOrder`: https://github.com/cloudflare/go/blob/cf/src/crypto/tls/cipher_suites.go#L271

This happens because of this check: https://github.com/cloudflare/go/blob/cf/src/crypto/tls/handshake_client.go#L100

Would it be possible to add an option to use these new cipher suites in ClientHello?

**Comment by Lekensteyn** [comment]
Hi! To secure the connection with PQ, we modified the key agreement. No changes are needed to the cipher suites.

If you only target servers with known support for specific PQ KEMs, you could use:
```go
conf := &tls.Config{
    CurvePreferences: []tls.CurveID{tls.X25519Kyber768Draft00},
}
```

In general I would recommend adding fallback support for non-PQ groups, e.g.:
```go
conf := &tls.Config{
    CurvePreferences: []tls.CurveID{tls.X25519Kyber768Draft00, tls.X25519, tls.CurveP256},
}
```
That way, the handshake won't fail, and an additional roundtrip for a Hello Retry Request (HRR) message allows the handshake to be completed without PQ support.

Edit: also worth noting that PQ requires TLS 1.3 support, it won't work with TLS 1.2 or older.

**Comment by ameshkov** [comment]
Oh, shame on me for thinking it should've been added to cipher suites.

It works great, thank you!
