### ISSUE TITLE
Kyber example incompatible with Google's kex implementation

### ISSUE THREAD

**Issue by filiptronicek** [cloudflare/go#174]
Hey there 👋 

I have been playing around with the example shared in the article [Experiment with post-quantum cryptography today](https://blog.cloudflare.com/experiment-with-pq/) and have noticed something unexpected: when I try to establish a TLS connection to a website with Kyber as the kex, it seems to only work on Cloudflare-enabled sites.

When I try changing the requested URL to something like `https://google.com`, it outputs the following:
```
HelloRetryRequest
Used 29
```

But when I try something on Cloudflare, like `cloudflare.com` or `gitlab.com`, I get the following, as expected:
```
Used X25519Kyber512Draft00
```

<details><summary>Example code used</summary>
<p>

```go
package main

import (
    "context"
    "crypto/tls"
    "fmt"
    "net/http"
)

func main() {
    req, err := http.NewRequestWithContext(
        context.WithValue(
            context.Background(),
            tls.CFEventHandlerContextKey{},
            func(ev tls.CFEvent) {
                switch e := ev.(type) {
                case tls.CFEventTLS13HRR:
                    fmt.Printf("HelloRetryRequest\n")
                case tls.CFEventTLS13NegotiatedKEX:
                    switch e.KEX {
                    case tls.X25519Kyber512Draft00:
                        fmt.Printf("Used X25519Kyber512Draft00\n")
                    default:
                        fmt.Printf("Used %d\n", e.KEX)
                    }
                }
            },
        ),
        "GET",
        "https://google.com",
        nil,
    )
    if err != nil {
        panic(err)
    }

    http.DefaultTransport.(*http.Transport).TLSClientConfig = &tls.Config{
        CurvePreferences: []tls.CurveID{tls.X25519Kyber512Draft00, tls.X25519},
    }

    if _, err = (&http.Client{}).Do(req); err != nil {
        fmt.Println(err)
    }
}


```

</p>
</details>

When trying to request these URLs inside of Chrome and Firefox, both seem to correctly use Kyber as well. This also works correctly in upstream boringssl (not the CF fork).

<img width="1919" alt="image" src="https://github.com/cloudflare/go/assets/29888641/62b7722a-68a2-4f9c-a3d9-1d2765f25e22">

I was not able to verify this against any other services besides Google and Cloudflare, since those seem to be the biggest current adopters.

**Comment by bwesterb** [comment]
Try `tls.X25519Kyber768Draft00` instead of `tls.X25519Kyber512Draft00` — Google (sensibly) only deployed [X25519Kyber768Draft00](https://datatracker.ietf.org/doc/draft-tls-westerbaan-xyber768d00/).

**Comment by filiptronicek** [comment]
@bwesterb that was totally it, sorry for my oversight (didn't notice the 768 vs 512 discrepancy), and thanks for the swift answer!

**Comment by bwesterb** [comment]
No problem. It’s confusing there are several choices
