### ISSUE TITLE
Not interoperable with boring_ssl or boringssl-pq

### ISSUE THREAD

**Issue by IMSterling** [cloudflare/go#178]
I am running a local server with vanilla boring_ssl and the CloudFlare fork of boring_ssl 
`bssl server -curves X25519Kyber768Draft00/X25519Kyber512Draft00 -accept 4433 -loop`

I have am then trying to connect to the server using the [Go demo code](https://blog.cloudflare.com/experiment-with-pq) which works when run against "https://pq.cloudflareresearch.com". 

Running against the bssl server continually returns `Error while connecting: NO_SHARED_GROUP
5148525200:error:1000010a:SSL routines:OPENSSL_internal:NO_SHARED_GROUP`

where I would expect these options to be interoperable. 

Please advise

**Comment by IMSterling** [comment]
[For followers of the thread] setting the curve preferences directly via the value with `CurvePreferences:       []tls.CurveID{tls.CurveID(25497)}` (for X25519Kyber768Draft00) resolves the issue

**Comment by bwesterb** [comment]
No need to use our BoringSSL fork: upstream BoringSSL supports X25519Kyber768Draft00 now.
