### ISSUE TITLE
Implement delegated credentials

### ISSUE THREAD

**Issue by claucece** [cloudflare/go#26]
Basically, I'll divide this task on:

- [x] Review the two PRs over tls-tris that implemented delegated credentials
- [x] Make the first skeleton from DC work with TLS 1.2, to understand the golang API
- [x] Switch to implementing for TLS 1.3 as per draft:
   - [x] Server Auth
   - [x] Client Auth
- [x] Add tests and verify the command line param works
- [x] Add other schemes to DC
- [ ] Generate draft test vectors

**Comment by claucece** [comment]
Current work at: https://github.com/cloudflare/go/tree/cf-delegated-credentials 

cc./ @chris-wood @armfazh @bwesterb

**Comment by bwesterb** [comment]
Looks very good.  Would you mind creating a PR on this repo so that it's easier to view/comment?

**Comment by claucece** [comment]
Yes! But I was going to start since 1.3, as to not clutter the PR.

**Comment by claucece** [comment]
The command line for dc is working now. This can be tried out: `bin/go run src/crypto/tls/generate_cert.go -ecdsa-curve P256 -host 127.0.0.1 -dc`

**Comment by claucece** [comment]
The draft vectors will be re-generated now with golang and boringssl.

**Comment by claucece** [comment]
I'll be moving this here: https://github.com/claucece/go-exp
