### ISSUE TITLE
Should we add a CI?

### ISSUE THREAD

**Issue by claucece** [cloudflare/go#27]
Do you think it will be worth adding a CI here? For testing on different archs... @bwesterb

**Comment by Lekensteyn** [comment]
It would be helpful to have to ensure that PRs do not cause regressions elsewhere, so 👍 for CI.

GitHub Actions supports Windows, Linux and macOS (https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions). It also claims to support ARM, but I could not quickly find documentation about that.

circl does use GitHub Actions for arm64, an example can be found here: https://github.com/cloudflare/circl/blob/master/.github/workflows/ci-actions.yml

**Comment by claucece** [comment]
Yes, I think using  GitHub Actions might be the right way. I'll integrate it ;)

**Comment by thomwiggers** [comment]
For ARM support, you need to provide self-hosted runners afaik.

**Comment by claucece** [comment]
Thank you @Lekensteyn
