### ISSUE TITLE
Improve CIRCL upgrade procedure

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/go#43]
One of the main differences between cfgo (there I said) and upstream go is that our fork includes CIRCL in the standard library. To updated CIRCL, we run a script called `cf-update-circl.py` that:
1. clones the master branch of github.com/cloudflare/circl;
1. copies its  contents into `src/circl`;
1. prunes non-package files and directories (e.g., `.git`, ASM generators, etc.); and
1. fixes imports (`github.com/cloudflare/circl/kem` -> `circl/kem` and so on, `golang.org/x/sys/cpu` to `internal/cpu`).

This process has three problems that I can see:
1. The script requires occasional maintenance, as changes to upstream CIRCL can break the build. This is inevitable, of course, but CIRCL is currently changing much more quickly than cfgo's requirements for CIRCL change. Instead of copying-then-pruning, we want to make sure that we only build the dependencies we need.
1. Import fix-ups are done by a simple search-and-replace, which is a bit icky because, in theory, it could change the code.
1. AFAICT there's no provenance of which version of CIRCL is running. This would be useful for debugging purposes.

There are two ways we can try to remedy this. The first (PR #40) is to use go modules to vendor CIRCL properly. This works pretty well, except that resolving dependencies shared by the standard library and CIRCL requires changing the standard library's dependencies. As we don't know what the side effects of these changes might be, we ought to consider these changes as "unsafe" in general.

With that option off the table, our best option is to improve the existing script. That work is tracked by PR #42.

**Comment by claucece** [comment]
I like the option of improving the existing script. 

Another question I have: do we need the whole CIRCL repo in cfgo? Is there a way in which maybe we can copy only the files needed and putting them on the correct crypto folders? 

This comes from an earlier question, as well, we had at the beginning of the PQ KEM exp: do we also need the whole golang std lib? or should we only need from there the crypto folder? For the PQ KEM, we decided to go with the whole golang's go, as it was easier.

I don't know the answers to this, so I'll leave this open ;)

**Comment by cjpatton** [comment]
> Another question I have: do we need the whole CIRCL repo in cfgo? Is there a way in which maybe we can copy only the files needed and putting them on the correct crypto folders?

We don't, though I'm not sure what the best way to copy only what we need would be. Still working this out.

**Comment by cjpatton** [comment]
Based on discussion on #42 it seems like there's a weak preference for sticking with the status quo, which is to copy everything and exclude things that break the build. The alternative of including only what we need is written up here: https://github.com/cloudflare/go/tree/cjpatton/cf-update-inclusive
