### ISSUE TITLE
Upstream Proposal

### ISSUE THREAD

**Issue by tarndt** [cloudflare/go#5]
Have these changes been submitted upstream? If not can we get an ETA? Thanks!

**Comment by vkrasnov** [comment]
You can see the RSA submission here:
https://go-review.googlesource.com/#/c/9253/
The EC submission is here:
https://go-review.googlesource.com/#/c/8968/
Although I need to update it as it is much improved here.

The AES-GCM will be submitted soon.

**Comment by tarndt** [comment]
>The AES-GCM will be submitted soon.

I wanted to follow up and see if this has been submitted?

**Comment by vkrasnov** [comment]
Yes it was. It will be upstreamed after go 1.5.
RSA was upstreamed, and EC is stuck on legal issues.

**Comment by adamleko** [comment]
If the EC cannot be merged upstream, will this repo continue to live and incorporate other upstream changes? It would be a real shame if the performance improvements die out due to legal technicalities.

**Comment by dahankzter** [comment]
Is this true? The ticket on google source says that it is merged. Does that mean upstream picked it?

**Comment by nathany** [comment]
See https://github.com/cloudflare/go/issues/8#issuecomment-146810886

**Comment by FiloSottile** [comment]
All current patches listed in https://github.com/cloudflare/go#backports landed in 1.6

This repo will usually always keep rebasing anything it adds on the latest stable
