### ISSUE TITLE
crypto/rsa: drop the primality check in crypto/rsa.Validate

### ISSUE THREAD

**Issue by zshenker** [cloudflare/go#6]
Any chance of pulling in https://github.com/golang/go/commit/7c7126cfeb82894229b9c3d5109e4b04e6cfde0c

**Comment by grittygrease** [comment]
Please submit a PR and discussion can happen there.

**Comment by FiloSottile** [comment]
That is merged in 1.5 and so in the new master. Open a PR to 1.4.3 if you are interested in seeing it pulled on top of our 1.4.
