### ISSUE TITLE
Add Wiki page for documing the rebase process

### ISSUE THREAD

**Issue by cjpatton** [cloudflare/go#60]

**Comment by claucece** [comment]
I did added something here: https://github.com/cloudflare/go/wiki/Starting-out#rebasing

There are many ways of rebasing, so might be good to unify that.

@Lekensteyn what you think?

**Comment by cjpatton** [comment]
LGTM!

**Comment by cjpatton** [comment]
I'll take the silence on this issue as rough consensus that it's been resolved. Whoever handles the next rebase will validate the instructions and adjust as needed.
