### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by chris-wood** [cloudflare/go#61]
Let's make sure the policy for interacting with one another is clear. [GitHub even made it easy for us!](https://docs.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-using-a-template)

**Comment by cjpatton** [comment]
Two points about: https://github.com/cloudflare/go/wiki/Code-of-Conduct
1. What does "dismissal from the repository" mean? Can the user be blocked from commenting or creating issues/PRs?
1. Since @claucece and I are admins of the repo, either of us could be a point of contact.

**Comment by claucece** [comment]
Added the new one here: https://github.com/cloudflare/go/wiki/Code-of-Conduct

**Comment by cjpatton** [comment]
LGTM. I move that we close out this issue, @chris-wood

**Comment by armfazh** [comment]
So lately but I discover this https://github.com/cloudflare/.github
