### ISSUE TITLE
Define an API for DCs

### ISSUE THREAD

**Issue by claucece** [cloudflare/go#67]
Currently, there is a callback for using DC: `GetDelegatedCredential`. This can be improved to:

- [x] Use the `GetCertificate` and `GetCertificateClient` callbacks to return the DCs as part of the Certificate structure
- [x] Allow the possibility of returning a list of DCs: the appropriate DC will be chosen by using the advertise signature algorithm on the ClientHello/Certificate Request extension.
- [x] Refactor the DC tests.

**Comment by claucece** [comment]
cc./ @armfazh @wbl

**Comment by claucece** [comment]
Related to #63

**Comment by cjpatton** [comment]
I like the idea of adding DCs to the `crypto/tls.Certificate` structure, since it allows us to expose DCs by whatever means is easiest to configure. Something like this?
```go
type Certificate struct {
   ...
   DCs [][]byte
   DCPrivateKeys []crypto.PrivateKey
}
```
so that `DCPrivateKeys[i]` is the private key of `DCs[i]` for all `0 <= i <= len(DCs)`?

**Comment by claucece** [comment]
@cjpatton check the latest pr: https://github.com/cloudflare/go/commit/dc791fdbeeacff13d3e1f076106a013fd56cd5f3

**Comment by cjpatton** [comment]
You're idea is much better than mine! I left some comments on the PR.

**Comment by claucece** [comment]
Merged now. Closing this.
