### ISSUE TITLE
Will it move to go1.5?

### ISSUE THREAD

**Issue by phuslu** [cloudflare/go#7]
Hello there,

Thank you all for the amazing works!

As you know, go1.5 rc1 come out today, so is there any chance to move these patches to go1.5 branch?

UPDATE: I forked the offical golang/go repo then cherry-picked the cloudflare commits to it here, https://github.com/phuslu/go
but maintain a homemade repo is nightmare, hope that cloudflare/go is possible to rebase to go1.5 in near future.

Regards,
Phus

**Comment by derekperkins** [comment]
:+1:

**Comment by FiloSottile** [comment]
Master is now based on 1.5.2
