### ISSUE TITLE
Packages instead of entire Go fork

### ISSUE THREAD

**Issue by trichner** [cloudflare/go#8]
Would it be possible to break down this repo into the packages necessary/modified?

i.e. such that one could: `import "github.com/cloudflare/go-aes-gcm"` as a drop-in for the `aes` package that's builtin.

This would most likely also resolve the issue of moving to go 1.5 .

**Comment by fd** [comment]
@vkrasnov any news on this. Or are you planning to push these changes upstream?

**Comment by vkrasnov** [comment]
AES-GCM and RSA are already upstream. Only EC left.

**Comment by fd** [comment]
Will EC land with 1.6? or is this still unclear. Awesome work btw.

**Comment by vkrasnov** [comment]
It is quite clear that it will not land on 1.6. But I believe you will see it in 1.7. I can't commit to that however, since it is a license issue with Intel.

**Comment by fd** [comment]
>  I can't commit to that however, since it is a license issue with Intel.

Oh, right forgot about that.

**Comment by FiloSottile** [comment]
All current patches listed in https://github.com/cloudflare/go#backports landed in 1.6

This repo will usually always keep rebasing anything it adds on the latest stable

**Comment by nathany** [comment]
Did EC land for 1.6?

**Comment by FiloSottile** [comment]
All patches on this tree as of go1.5.3-cloudflare1 landed in 1.6.

I guess that makes separate packages not that useful, too, so I'll close the issue. Reopen if you disagree.

**Comment by nathany** [comment]
Awesome. Thanks Filippo.
